# mypy: ignore-errors
from collections.abc import Generator
from contextlib import contextmanager
from typing import Any, Literal
from aiogram_i18n import LazyProxy

class I18nContext(I18nStub):
    def get(self, key: str, /, **kwargs: Any) -> str: ...
    async def set_locale(self, locale: str, **kwargs: Any) -> None: ...
    @contextmanager
    def use_locale(self, locale: str) -> Generator[I18nContext, None, None]: ...
    @contextmanager
    def use_context(self, **kwargs: Any) -> Generator[I18nContext, None, None]: ...
    def set_context(self, **kwargs: Any) -> None: ...

class LazyFactory(I18nStub):
    key_separator: str

    def set_separator(self, key_separator: str) -> None: ...
    def __call__(self, key: str, /, **kwargs: dict[str, Any]) -> LazyProxy: ...

L: LazyFactory

class I18nStub:
    class __Mood:
        @staticmethod
        def unset(**kwargs: Any) -> Literal["Не указано"]: ...
        @staticmethod
        def awesome(**kwargs: Any) -> Literal["Прекрасно"]: ...
        @staticmethod
        def greet(**kwargs: Any) -> Literal["Здорово"]: ...
        @staticmethod
        def good(**kwargs: Any) -> Literal["Хорошо"]: ...
        @staticmethod
        def okay(**kwargs: Any) -> Literal["Обычно"]: ...
        @staticmethod
        def bad(**kwargs: Any) -> Literal["Плохо"]: ...
        @staticmethod
        def terrible(**kwargs: Any) -> Literal["Ужасно"]: ...

    mood = __Mood()

    @staticmethod
    def month_1(**kwargs: Any) -> Literal["Январь"]: ...
    @staticmethod
    def month_2(**kwargs: Any) -> Literal["Февраль"]: ...
    @staticmethod
    def month_3(**kwargs: Any) -> Literal["Март"]: ...
    @staticmethod
    def month_4(**kwargs: Any) -> Literal["Апрель"]: ...
    @staticmethod
    def month_5(**kwargs: Any) -> Literal["Май"]: ...
    @staticmethod
    def month_6(**kwargs: Any) -> Literal["Июнь"]: ...
    @staticmethod
    def month_7(**kwargs: Any) -> Literal["Июль"]: ...
    @staticmethod
    def month_8(**kwargs: Any) -> Literal["Август"]: ...
    @staticmethod
    def month_9(**kwargs: Any) -> Literal["Сентябрь"]: ...
    @staticmethod
    def month_10(**kwargs: Any) -> Literal["Октябрь"]: ...
    @staticmethod
    def month_11(**kwargs: Any) -> Literal["Ноябрь"]: ...
    @staticmethod
    def month_12(**kwargs: Any) -> Literal["Декабрь"]: ...

    class __Error:
        @staticmethod
        def button_wrong_user(**kwargs: Any) -> Literal["Не твоя кнопка"]: ...

    error = __Error()

    @staticmethod
    def mood_month(
        *, year: Any, month: Any, **kwargs: Any
    ) -> Literal[
        '<tg-emoji emoji-id="5431897022456145283">📆</tg-emoji> Календарь настроения'
    ]: ...
    @staticmethod
    def mood_day(
        *, year: Any, month: Any, day: Any, mood: Any, mood_emoji: Any, **kwargs: Any
    ) -> Literal[
        '<tg-emoji emoji-id="5471978009449731768">👉</tg-emoji> <b>{ $year }, { $month }, { $day }</b>'
    ]: ...
    @staticmethod
    def mood_marker_selected(
        *, marker: Any, **kwargs: Any
    ) -> Literal["✏️ Выбрано: { $marker }"]: ...
    @staticmethod
    def clear(**kwargs: Any) -> Literal["Очистить"]: ...
