"""upd mood table: new days_notes

Revision ID: 3ddc37becb83
Revises: d83c93cf90ba
Create Date: 2026-01-11 12:56:37.725699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddc37becb83'
down_revision: Union[str, Sequence[str], None] = 'd83c93cf90ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('days_notes', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood', 'days_notes')
    # ### end Alembic commands ###
