"""truncate user_last_message

Revision ID: 43b2aeed9749
Revises: 940c5f50a426
Create Date: 2026-01-14 11:55:42.607600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b2aeed9749'
down_revision: Union[str, Sequence[str], None] = '940c5f50a426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE user_last_message;")
    op.execute("UPDATE mood_config SET notify_chat_topic_id = 0;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
