"""new table: `mood_config`

Revision ID: 8d80c0ac1544
Revises: 721d074acac5
Create Date: 2026-01-10 11:58:33.346467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision: str = '8d80c0ac1544'
down_revision: Union[str, Sequence[str], None] = '721d074acac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_config',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('notify_state', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notify_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('notify_chat_topic_id', sa.BigInteger(), nullable=True),
    sa.Column('notify_time', sa.Time(), server_default=sa.text("'00:00'"), nullable=False),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=True, nullable=False),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood_config')
    # ### end Alembic commands ###
