"""new column: mood_config.notify_current_day

Revision ID: 940c5f50a426
Revises: ebe749f7a365
Create Date: 2026-01-14 11:08:59.055118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940c5f50a426'
down_revision: Union[str, Sequence[str], None] = 'ebe749f7a365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_config', sa.Column('notify_current_day', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_config', 'notify_current_day')
    # ### end Alembic commands ###
