"""new table: `user_last_message`

Revision ID: d83c93cf90ba
Revises: 8d80c0ac1544
Create Date: 2026-01-11 11:41:51.029712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc

# revision identifiers, used by Alembic.
revision: str = 'd83c93cf90ba'
down_revision: Union[str, Sequence[str], None] = '8d80c0ac1544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_last_message',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('message', sa.JSON(), nullable=False),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=True, nullable=False),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_last_message')
    # ### end Alembic commands ###
