"""default created_at and on_update

Revision ID: ff2734781e60
Revises: 000000000000
Create Date: 2026-01-08 01:01:45.620401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utc import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = 'ff2734781e60'
down_revision: Union[str, Sequence[str], None] = '000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, autoincrement=True))
    op.add_column('mood', sa.Column('updated_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, autoincrement=True))
    op.add_column('users', sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, autoincrement=True))
    op.add_column('users', sa.Column('updated_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, autoincrement=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('mood', 'updated_at')
    op.drop_column('mood', 'created_at')
    # ### end Alembic commands ###
